// Slugs curados que se muestran en la sección "Best Sellers" del home.
// Compartido entre BackInStock (home) y la página SALE, que excluye estos
// para no repetir productos y destacar los que no aparecen en el home.
export const BEST_SELLERS_SLUGS = [
  'per-aspera-ad-astra-zippo',
  'jersey-fileteado-x-alfredo-genovese',
  'no-service-for-the-faithless-hoodie',
  'lettering-melange-jort',
  'no-service-for-the-faithless-white',
  'no-service-for-the-faithless-black',
  'no-service-for-the-faithless-grey',
  'no-service-for-the-faithless-green',
  'baby-come-back-black',
  'no-love-only-style-tops',
  'trucker-cap-baby-come-back',
  'lettering-pink-jort',
  'race-tee',
  'mesh-realtree-pink-tee',
  'mesh-realtree-tee',
  'lettering-graphite-hoodie',
  'lettering-graphite-jort',
  'jort-cargo-realtree-pink',
  'jort-cargo-realtree-beige',
  'fleece-jacket-v1-negrogris',
  'hoodie-shield-olive',
  'sweatpants-bombe-bordo',
  'knitted-tshirt-sand',
  'sleeveless-ranglan-white',
  'sleeveless-ranglan-militar-green',
  'sleeveless-ranglan-grey',
  'sleeveless-ranglan-black',
  'raglan-tee-tribal-cross',
  'hypestation-white-tee',
  'hypestation-black-tee',
  'honda-white-tee',
  'honda-black-tee',
  'skyline-tee',
  'aerogrey-tees',
  'mesh-camo-blue-tee',
  'mesh-camo-grey-tee',
  'hoodie-stay-hustle',
];
